require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActividadRolsController do

  # This should return the minimal set of attributes required to create a valid
  # ActividadRol. As you add validations to ActividadRol, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActividadRolsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all actividad_rols as @actividad_rols" do
      actividad_rol = ActividadRol.create! valid_attributes
      get :index, {}, valid_session
      assigns(:actividad_rols).should eq([actividad_rol])
    end
  end

  describe "GET show" do
    it "assigns the requested actividad_rol as @actividad_rol" do
      actividad_rol = ActividadRol.create! valid_attributes
      get :show, {:id => actividad_rol.to_param}, valid_session
      assigns(:actividad_rol).should eq(actividad_rol)
    end
  end

  describe "GET new" do
    it "assigns a new actividad_rol as @actividad_rol" do
      get :new, {}, valid_session
      assigns(:actividad_rol).should be_a_new(ActividadRol)
    end
  end

  describe "GET edit" do
    it "assigns the requested actividad_rol as @actividad_rol" do
      actividad_rol = ActividadRol.create! valid_attributes
      get :edit, {:id => actividad_rol.to_param}, valid_session
      assigns(:actividad_rol).should eq(actividad_rol)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ActividadRol" do
        expect {
          post :create, {:actividad_rol => valid_attributes}, valid_session
        }.to change(ActividadRol, :count).by(1)
      end

      it "assigns a newly created actividad_rol as @actividad_rol" do
        post :create, {:actividad_rol => valid_attributes}, valid_session
        assigns(:actividad_rol).should be_a(ActividadRol)
        assigns(:actividad_rol).should be_persisted
      end

      it "redirects to the created actividad_rol" do
        post :create, {:actividad_rol => valid_attributes}, valid_session
        response.should redirect_to(ActividadRol.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved actividad_rol as @actividad_rol" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActividadRol.any_instance.stub(:save).and_return(false)
        post :create, {:actividad_rol => {}}, valid_session
        assigns(:actividad_rol).should be_a_new(ActividadRol)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActividadRol.any_instance.stub(:save).and_return(false)
        post :create, {:actividad_rol => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested actividad_rol" do
        actividad_rol = ActividadRol.create! valid_attributes
        # Assuming there are no other actividad_rols in the database, this
        # specifies that the ActividadRol created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ActividadRol.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => actividad_rol.to_param, :actividad_rol => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested actividad_rol as @actividad_rol" do
        actividad_rol = ActividadRol.create! valid_attributes
        put :update, {:id => actividad_rol.to_param, :actividad_rol => valid_attributes}, valid_session
        assigns(:actividad_rol).should eq(actividad_rol)
      end

      it "redirects to the actividad_rol" do
        actividad_rol = ActividadRol.create! valid_attributes
        put :update, {:id => actividad_rol.to_param, :actividad_rol => valid_attributes}, valid_session
        response.should redirect_to(actividad_rol)
      end
    end

    describe "with invalid params" do
      it "assigns the actividad_rol as @actividad_rol" do
        actividad_rol = ActividadRol.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActividadRol.any_instance.stub(:save).and_return(false)
        put :update, {:id => actividad_rol.to_param, :actividad_rol => {}}, valid_session
        assigns(:actividad_rol).should eq(actividad_rol)
      end

      it "re-renders the 'edit' template" do
        actividad_rol = ActividadRol.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActividadRol.any_instance.stub(:save).and_return(false)
        put :update, {:id => actividad_rol.to_param, :actividad_rol => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested actividad_rol" do
      actividad_rol = ActividadRol.create! valid_attributes
      expect {
        delete :destroy, {:id => actividad_rol.to_param}, valid_session
      }.to change(ActividadRol, :count).by(-1)
    end

    it "redirects to the actividad_rols list" do
      actividad_rol = ActividadRol.create! valid_attributes
      delete :destroy, {:id => actividad_rol.to_param}, valid_session
      response.should redirect_to(actividad_rols_url)
    end
  end

end
