require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompuertusController do

  # This should return the minimal set of attributes required to create a valid
  # Compuertu. As you add validations to Compuertu, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompuertusController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all compuertus as @compuertus" do
      compuertu = Compuertu.create! valid_attributes
      get :index, {}, valid_session
      assigns(:compuertus).should eq([compuertu])
    end
  end

  describe "GET show" do
    it "assigns the requested compuertu as @compuertu" do
      compuertu = Compuertu.create! valid_attributes
      get :show, {:id => compuertu.to_param}, valid_session
      assigns(:compuertu).should eq(compuertu)
    end
  end

  describe "GET new" do
    it "assigns a new compuertu as @compuertu" do
      get :new, {}, valid_session
      assigns(:compuertu).should be_a_new(Compuertu)
    end
  end

  describe "GET edit" do
    it "assigns the requested compuertu as @compuertu" do
      compuertu = Compuertu.create! valid_attributes
      get :edit, {:id => compuertu.to_param}, valid_session
      assigns(:compuertu).should eq(compuertu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Compuertu" do
        expect {
          post :create, {:compuertu => valid_attributes}, valid_session
        }.to change(Compuertu, :count).by(1)
      end

      it "assigns a newly created compuertu as @compuertu" do
        post :create, {:compuertu => valid_attributes}, valid_session
        assigns(:compuertu).should be_a(Compuertu)
        assigns(:compuertu).should be_persisted
      end

      it "redirects to the created compuertu" do
        post :create, {:compuertu => valid_attributes}, valid_session
        response.should redirect_to(Compuertu.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved compuertu as @compuertu" do
        # Trigger the behavior that occurs when invalid params are submitted
        Compuertu.any_instance.stub(:save).and_return(false)
        post :create, {:compuertu => {}}, valid_session
        assigns(:compuertu).should be_a_new(Compuertu)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Compuertu.any_instance.stub(:save).and_return(false)
        post :create, {:compuertu => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested compuertu" do
        compuertu = Compuertu.create! valid_attributes
        # Assuming there are no other compuertus in the database, this
        # specifies that the Compuertu created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Compuertu.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => compuertu.to_param, :compuertu => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested compuertu as @compuertu" do
        compuertu = Compuertu.create! valid_attributes
        put :update, {:id => compuertu.to_param, :compuertu => valid_attributes}, valid_session
        assigns(:compuertu).should eq(compuertu)
      end

      it "redirects to the compuertu" do
        compuertu = Compuertu.create! valid_attributes
        put :update, {:id => compuertu.to_param, :compuertu => valid_attributes}, valid_session
        response.should redirect_to(compuertu)
      end
    end

    describe "with invalid params" do
      it "assigns the compuertu as @compuertu" do
        compuertu = Compuertu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Compuertu.any_instance.stub(:save).and_return(false)
        put :update, {:id => compuertu.to_param, :compuertu => {}}, valid_session
        assigns(:compuertu).should eq(compuertu)
      end

      it "re-renders the 'edit' template" do
        compuertu = Compuertu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Compuertu.any_instance.stub(:save).and_return(false)
        put :update, {:id => compuertu.to_param, :compuertu => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested compuertu" do
      compuertu = Compuertu.create! valid_attributes
      expect {
        delete :destroy, {:id => compuertu.to_param}, valid_session
      }.to change(Compuertu, :count).by(-1)
    end

    it "redirects to the compuertus list" do
      compuertu = Compuertu.create! valid_attributes
      delete :destroy, {:id => compuertu.to_param}, valid_session
      response.should redirect_to(compuertus_url)
    end
  end

end
