require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlantillasController do

  # This should return the minimal set of attributes required to create a valid
  # Plantilla. As you add validations to Plantilla, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlantillasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all plantillas as @plantillas" do
      plantilla = Plantilla.create! valid_attributes
      get :index, {}, valid_session
      assigns(:plantillas).should eq([plantilla])
    end
  end

  describe "GET show" do
    it "assigns the requested plantilla as @plantilla" do
      plantilla = Plantilla.create! valid_attributes
      get :show, {:id => plantilla.to_param}, valid_session
      assigns(:plantilla).should eq(plantilla)
    end
  end

  describe "GET new" do
    it "assigns a new plantilla as @plantilla" do
      get :new, {}, valid_session
      assigns(:plantilla).should be_a_new(Plantilla)
    end
  end

  describe "GET edit" do
    it "assigns the requested plantilla as @plantilla" do
      plantilla = Plantilla.create! valid_attributes
      get :edit, {:id => plantilla.to_param}, valid_session
      assigns(:plantilla).should eq(plantilla)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Plantilla" do
        expect {
          post :create, {:plantilla => valid_attributes}, valid_session
        }.to change(Plantilla, :count).by(1)
      end

      it "assigns a newly created plantilla as @plantilla" do
        post :create, {:plantilla => valid_attributes}, valid_session
        assigns(:plantilla).should be_a(Plantilla)
        assigns(:plantilla).should be_persisted
      end

      it "redirects to the created plantilla" do
        post :create, {:plantilla => valid_attributes}, valid_session
        response.should redirect_to(Plantilla.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plantilla as @plantilla" do
        # Trigger the behavior that occurs when invalid params are submitted
        Plantilla.any_instance.stub(:save).and_return(false)
        post :create, {:plantilla => {}}, valid_session
        assigns(:plantilla).should be_a_new(Plantilla)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Plantilla.any_instance.stub(:save).and_return(false)
        post :create, {:plantilla => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested plantilla" do
        plantilla = Plantilla.create! valid_attributes
        # Assuming there are no other plantillas in the database, this
        # specifies that the Plantilla created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Plantilla.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => plantilla.to_param, :plantilla => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested plantilla as @plantilla" do
        plantilla = Plantilla.create! valid_attributes
        put :update, {:id => plantilla.to_param, :plantilla => valid_attributes}, valid_session
        assigns(:plantilla).should eq(plantilla)
      end

      it "redirects to the plantilla" do
        plantilla = Plantilla.create! valid_attributes
        put :update, {:id => plantilla.to_param, :plantilla => valid_attributes}, valid_session
        response.should redirect_to(plantilla)
      end
    end

    describe "with invalid params" do
      it "assigns the plantilla as @plantilla" do
        plantilla = Plantilla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Plantilla.any_instance.stub(:save).and_return(false)
        put :update, {:id => plantilla.to_param, :plantilla => {}}, valid_session
        assigns(:plantilla).should eq(plantilla)
      end

      it "re-renders the 'edit' template" do
        plantilla = Plantilla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Plantilla.any_instance.stub(:save).and_return(false)
        put :update, {:id => plantilla.to_param, :plantilla => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plantilla" do
      plantilla = Plantilla.create! valid_attributes
      expect {
        delete :destroy, {:id => plantilla.to_param}, valid_session
      }.to change(Plantilla, :count).by(-1)
    end

    it "redirects to the plantillas list" do
      plantilla = Plantilla.create! valid_attributes
      delete :destroy, {:id => plantilla.to_param}, valid_session
      response.should redirect_to(plantillas_url)
    end
  end

end
