require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProyectoArtefactosController do

  # This should return the minimal set of attributes required to create a valid
  # ProyectoArtefacto. As you add validations to ProyectoArtefacto, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProyectoArtefactosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all proyecto_artefactos as @proyecto_artefactos" do
      proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:proyecto_artefactos).should eq([proyecto_artefacto])
    end
  end

  describe "GET show" do
    it "assigns the requested proyecto_artefacto as @proyecto_artefacto" do
      proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
      get :show, {:id => proyecto_artefacto.to_param}, valid_session
      assigns(:proyecto_artefacto).should eq(proyecto_artefacto)
    end
  end

  describe "GET new" do
    it "assigns a new proyecto_artefacto as @proyecto_artefacto" do
      get :new, {}, valid_session
      assigns(:proyecto_artefacto).should be_a_new(ProyectoArtefacto)
    end
  end

  describe "GET edit" do
    it "assigns the requested proyecto_artefacto as @proyecto_artefacto" do
      proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
      get :edit, {:id => proyecto_artefacto.to_param}, valid_session
      assigns(:proyecto_artefacto).should eq(proyecto_artefacto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProyectoArtefacto" do
        expect {
          post :create, {:proyecto_artefacto => valid_attributes}, valid_session
        }.to change(ProyectoArtefacto, :count).by(1)
      end

      it "assigns a newly created proyecto_artefacto as @proyecto_artefacto" do
        post :create, {:proyecto_artefacto => valid_attributes}, valid_session
        assigns(:proyecto_artefacto).should be_a(ProyectoArtefacto)
        assigns(:proyecto_artefacto).should be_persisted
      end

      it "redirects to the created proyecto_artefacto" do
        post :create, {:proyecto_artefacto => valid_attributes}, valid_session
        response.should redirect_to(ProyectoArtefacto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved proyecto_artefacto as @proyecto_artefacto" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectoArtefacto.any_instance.stub(:save).and_return(false)
        post :create, {:proyecto_artefacto => {}}, valid_session
        assigns(:proyecto_artefacto).should be_a_new(ProyectoArtefacto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectoArtefacto.any_instance.stub(:save).and_return(false)
        post :create, {:proyecto_artefacto => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested proyecto_artefacto" do
        proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
        # Assuming there are no other proyecto_artefactos in the database, this
        # specifies that the ProyectoArtefacto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProyectoArtefacto.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => proyecto_artefacto.to_param, :proyecto_artefacto => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested proyecto_artefacto as @proyecto_artefacto" do
        proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
        put :update, {:id => proyecto_artefacto.to_param, :proyecto_artefacto => valid_attributes}, valid_session
        assigns(:proyecto_artefacto).should eq(proyecto_artefacto)
      end

      it "redirects to the proyecto_artefacto" do
        proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
        put :update, {:id => proyecto_artefacto.to_param, :proyecto_artefacto => valid_attributes}, valid_session
        response.should redirect_to(proyecto_artefacto)
      end
    end

    describe "with invalid params" do
      it "assigns the proyecto_artefacto as @proyecto_artefacto" do
        proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectoArtefacto.any_instance.stub(:save).and_return(false)
        put :update, {:id => proyecto_artefacto.to_param, :proyecto_artefacto => {}}, valid_session
        assigns(:proyecto_artefacto).should eq(proyecto_artefacto)
      end

      it "re-renders the 'edit' template" do
        proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectoArtefacto.any_instance.stub(:save).and_return(false)
        put :update, {:id => proyecto_artefacto.to_param, :proyecto_artefacto => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested proyecto_artefacto" do
      proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
      expect {
        delete :destroy, {:id => proyecto_artefacto.to_param}, valid_session
      }.to change(ProyectoArtefacto, :count).by(-1)
    end

    it "redirects to the proyecto_artefactos list" do
      proyecto_artefacto = ProyectoArtefacto.create! valid_attributes
      delete :destroy, {:id => proyecto_artefacto.to_param}, valid_session
      response.should redirect_to(proyecto_artefactos_url)
    end
  end

end
