require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProyectoUsuariosController do

  # This should return the minimal set of attributes required to create a valid
  # ProyectoUsuario. As you add validations to ProyectoUsuario, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProyectoUsuariosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all proyecto_usuarios as @proyecto_usuarios" do
      proyecto_usuario = ProyectoUsuario.create! valid_attributes
      get :index, {}, valid_session
      assigns(:proyecto_usuarios).should eq([proyecto_usuario])
    end
  end

  describe "GET show" do
    it "assigns the requested proyecto_usuario as @proyecto_usuario" do
      proyecto_usuario = ProyectoUsuario.create! valid_attributes
      get :show, {:id => proyecto_usuario.to_param}, valid_session
      assigns(:proyecto_usuario).should eq(proyecto_usuario)
    end
  end

  describe "GET new" do
    it "assigns a new proyecto_usuario as @proyecto_usuario" do
      get :new, {}, valid_session
      assigns(:proyecto_usuario).should be_a_new(ProyectoUsuario)
    end
  end

  describe "GET edit" do
    it "assigns the requested proyecto_usuario as @proyecto_usuario" do
      proyecto_usuario = ProyectoUsuario.create! valid_attributes
      get :edit, {:id => proyecto_usuario.to_param}, valid_session
      assigns(:proyecto_usuario).should eq(proyecto_usuario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProyectoUsuario" do
        expect {
          post :create, {:proyecto_usuario => valid_attributes}, valid_session
        }.to change(ProyectoUsuario, :count).by(1)
      end

      it "assigns a newly created proyecto_usuario as @proyecto_usuario" do
        post :create, {:proyecto_usuario => valid_attributes}, valid_session
        assigns(:proyecto_usuario).should be_a(ProyectoUsuario)
        assigns(:proyecto_usuario).should be_persisted
      end

      it "redirects to the created proyecto_usuario" do
        post :create, {:proyecto_usuario => valid_attributes}, valid_session
        response.should redirect_to(ProyectoUsuario.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved proyecto_usuario as @proyecto_usuario" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectoUsuario.any_instance.stub(:save).and_return(false)
        post :create, {:proyecto_usuario => {}}, valid_session
        assigns(:proyecto_usuario).should be_a_new(ProyectoUsuario)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectoUsuario.any_instance.stub(:save).and_return(false)
        post :create, {:proyecto_usuario => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested proyecto_usuario" do
        proyecto_usuario = ProyectoUsuario.create! valid_attributes
        # Assuming there are no other proyecto_usuarios in the database, this
        # specifies that the ProyectoUsuario created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProyectoUsuario.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => proyecto_usuario.to_param, :proyecto_usuario => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested proyecto_usuario as @proyecto_usuario" do
        proyecto_usuario = ProyectoUsuario.create! valid_attributes
        put :update, {:id => proyecto_usuario.to_param, :proyecto_usuario => valid_attributes}, valid_session
        assigns(:proyecto_usuario).should eq(proyecto_usuario)
      end

      it "redirects to the proyecto_usuario" do
        proyecto_usuario = ProyectoUsuario.create! valid_attributes
        put :update, {:id => proyecto_usuario.to_param, :proyecto_usuario => valid_attributes}, valid_session
        response.should redirect_to(proyecto_usuario)
      end
    end

    describe "with invalid params" do
      it "assigns the proyecto_usuario as @proyecto_usuario" do
        proyecto_usuario = ProyectoUsuario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectoUsuario.any_instance.stub(:save).and_return(false)
        put :update, {:id => proyecto_usuario.to_param, :proyecto_usuario => {}}, valid_session
        assigns(:proyecto_usuario).should eq(proyecto_usuario)
      end

      it "re-renders the 'edit' template" do
        proyecto_usuario = ProyectoUsuario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectoUsuario.any_instance.stub(:save).and_return(false)
        put :update, {:id => proyecto_usuario.to_param, :proyecto_usuario => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested proyecto_usuario" do
      proyecto_usuario = ProyectoUsuario.create! valid_attributes
      expect {
        delete :destroy, {:id => proyecto_usuario.to_param}, valid_session
      }.to change(ProyectoUsuario, :count).by(-1)
    end

    it "redirects to the proyecto_usuarios list" do
      proyecto_usuario = ProyectoUsuario.create! valid_attributes
      delete :destroy, {:id => proyecto_usuario.to_param}, valid_session
      response.should redirect_to(proyecto_usuarios_url)
    end
  end

end
