require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TareaPresedenciaController do

  # This should return the minimal set of attributes required to create a valid
  # TareaPresedencium. As you add validations to TareaPresedencium, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TareaPresedenciaController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tarea_presedencia as @tarea_presedencia" do
      tarea_presedencium = TareaPresedencium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tarea_presedencia).should eq([tarea_presedencium])
    end
  end

  describe "GET show" do
    it "assigns the requested tarea_presedencium as @tarea_presedencium" do
      tarea_presedencium = TareaPresedencium.create! valid_attributes
      get :show, {:id => tarea_presedencium.to_param}, valid_session
      assigns(:tarea_presedencium).should eq(tarea_presedencium)
    end
  end

  describe "GET new" do
    it "assigns a new tarea_presedencium as @tarea_presedencium" do
      get :new, {}, valid_session
      assigns(:tarea_presedencium).should be_a_new(TareaPresedencium)
    end
  end

  describe "GET edit" do
    it "assigns the requested tarea_presedencium as @tarea_presedencium" do
      tarea_presedencium = TareaPresedencium.create! valid_attributes
      get :edit, {:id => tarea_presedencium.to_param}, valid_session
      assigns(:tarea_presedencium).should eq(tarea_presedencium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TareaPresedencium" do
        expect {
          post :create, {:tarea_presedencium => valid_attributes}, valid_session
        }.to change(TareaPresedencium, :count).by(1)
      end

      it "assigns a newly created tarea_presedencium as @tarea_presedencium" do
        post :create, {:tarea_presedencium => valid_attributes}, valid_session
        assigns(:tarea_presedencium).should be_a(TareaPresedencium)
        assigns(:tarea_presedencium).should be_persisted
      end

      it "redirects to the created tarea_presedencium" do
        post :create, {:tarea_presedencium => valid_attributes}, valid_session
        response.should redirect_to(TareaPresedencium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tarea_presedencium as @tarea_presedencium" do
        # Trigger the behavior that occurs when invalid params are submitted
        TareaPresedencium.any_instance.stub(:save).and_return(false)
        post :create, {:tarea_presedencium => {}}, valid_session
        assigns(:tarea_presedencium).should be_a_new(TareaPresedencium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TareaPresedencium.any_instance.stub(:save).and_return(false)
        post :create, {:tarea_presedencium => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tarea_presedencium" do
        tarea_presedencium = TareaPresedencium.create! valid_attributes
        # Assuming there are no other tarea_presedencia in the database, this
        # specifies that the TareaPresedencium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TareaPresedencium.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tarea_presedencium.to_param, :tarea_presedencium => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tarea_presedencium as @tarea_presedencium" do
        tarea_presedencium = TareaPresedencium.create! valid_attributes
        put :update, {:id => tarea_presedencium.to_param, :tarea_presedencium => valid_attributes}, valid_session
        assigns(:tarea_presedencium).should eq(tarea_presedencium)
      end

      it "redirects to the tarea_presedencium" do
        tarea_presedencium = TareaPresedencium.create! valid_attributes
        put :update, {:id => tarea_presedencium.to_param, :tarea_presedencium => valid_attributes}, valid_session
        response.should redirect_to(tarea_presedencium)
      end
    end

    describe "with invalid params" do
      it "assigns the tarea_presedencium as @tarea_presedencium" do
        tarea_presedencium = TareaPresedencium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TareaPresedencium.any_instance.stub(:save).and_return(false)
        put :update, {:id => tarea_presedencium.to_param, :tarea_presedencium => {}}, valid_session
        assigns(:tarea_presedencium).should eq(tarea_presedencium)
      end

      it "re-renders the 'edit' template" do
        tarea_presedencium = TareaPresedencium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TareaPresedencium.any_instance.stub(:save).and_return(false)
        put :update, {:id => tarea_presedencium.to_param, :tarea_presedencium => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tarea_presedencium" do
      tarea_presedencium = TareaPresedencium.create! valid_attributes
      expect {
        delete :destroy, {:id => tarea_presedencium.to_param}, valid_session
      }.to change(TareaPresedencium, :count).by(-1)
    end

    it "redirects to the tarea_presedencia list" do
      tarea_presedencium = TareaPresedencium.create! valid_attributes
      delete :destroy, {:id => tarea_presedencium.to_param}, valid_session
      response.should redirect_to(tarea_presedencia_url)
    end
  end

end
