require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TareaParticipantesController do

  # This should return the minimal set of attributes required to create a valid
  # TareaParticipante. As you add validations to TareaParticipante, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TareaParticipantesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tarea_participantes as @tarea_participantes" do
      tarea_participante = TareaParticipante.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tarea_participantes).should eq([tarea_participante])
    end
  end

  describe "GET show" do
    it "assigns the requested tarea_participante as @tarea_participante" do
      tarea_participante = TareaParticipante.create! valid_attributes
      get :show, {:id => tarea_participante.to_param}, valid_session
      assigns(:tarea_participante).should eq(tarea_participante)
    end
  end

  describe "GET new" do
    it "assigns a new tarea_participante as @tarea_participante" do
      get :new, {}, valid_session
      assigns(:tarea_participante).should be_a_new(TareaParticipante)
    end
  end

  describe "GET edit" do
    it "assigns the requested tarea_participante as @tarea_participante" do
      tarea_participante = TareaParticipante.create! valid_attributes
      get :edit, {:id => tarea_participante.to_param}, valid_session
      assigns(:tarea_participante).should eq(tarea_participante)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TareaParticipante" do
        expect {
          post :create, {:tarea_participante => valid_attributes}, valid_session
        }.to change(TareaParticipante, :count).by(1)
      end

      it "assigns a newly created tarea_participante as @tarea_participante" do
        post :create, {:tarea_participante => valid_attributes}, valid_session
        assigns(:tarea_participante).should be_a(TareaParticipante)
        assigns(:tarea_participante).should be_persisted
      end

      it "redirects to the created tarea_participante" do
        post :create, {:tarea_participante => valid_attributes}, valid_session
        response.should redirect_to(TareaParticipante.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tarea_participante as @tarea_participante" do
        # Trigger the behavior that occurs when invalid params are submitted
        TareaParticipante.any_instance.stub(:save).and_return(false)
        post :create, {:tarea_participante => {}}, valid_session
        assigns(:tarea_participante).should be_a_new(TareaParticipante)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TareaParticipante.any_instance.stub(:save).and_return(false)
        post :create, {:tarea_participante => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tarea_participante" do
        tarea_participante = TareaParticipante.create! valid_attributes
        # Assuming there are no other tarea_participantes in the database, this
        # specifies that the TareaParticipante created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TareaParticipante.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tarea_participante.to_param, :tarea_participante => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tarea_participante as @tarea_participante" do
        tarea_participante = TareaParticipante.create! valid_attributes
        put :update, {:id => tarea_participante.to_param, :tarea_participante => valid_attributes}, valid_session
        assigns(:tarea_participante).should eq(tarea_participante)
      end

      it "redirects to the tarea_participante" do
        tarea_participante = TareaParticipante.create! valid_attributes
        put :update, {:id => tarea_participante.to_param, :tarea_participante => valid_attributes}, valid_session
        response.should redirect_to(tarea_participante)
      end
    end

    describe "with invalid params" do
      it "assigns the tarea_participante as @tarea_participante" do
        tarea_participante = TareaParticipante.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TareaParticipante.any_instance.stub(:save).and_return(false)
        put :update, {:id => tarea_participante.to_param, :tarea_participante => {}}, valid_session
        assigns(:tarea_participante).should eq(tarea_participante)
      end

      it "re-renders the 'edit' template" do
        tarea_participante = TareaParticipante.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TareaParticipante.any_instance.stub(:save).and_return(false)
        put :update, {:id => tarea_participante.to_param, :tarea_participante => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tarea_participante" do
      tarea_participante = TareaParticipante.create! valid_attributes
      expect {
        delete :destroy, {:id => tarea_participante.to_param}, valid_session
      }.to change(TareaParticipante, :count).by(-1)
    end

    it "redirects to the tarea_participantes list" do
      tarea_participante = TareaParticipante.create! valid_attributes
      delete :destroy, {:id => tarea_participante.to_param}, valid_session
      response.should redirect_to(tarea_participantes_url)
    end
  end

end
