require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TareaRevisionsController do

  # This should return the minimal set of attributes required to create a valid
  # TareaRevision. As you add validations to TareaRevision, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TareaRevisionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tarea_revisions as @tarea_revisions" do
      tarea_revision = TareaRevision.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tarea_revisions).should eq([tarea_revision])
    end
  end

  describe "GET show" do
    it "assigns the requested tarea_revision as @tarea_revision" do
      tarea_revision = TareaRevision.create! valid_attributes
      get :show, {:id => tarea_revision.to_param}, valid_session
      assigns(:tarea_revision).should eq(tarea_revision)
    end
  end

  describe "GET new" do
    it "assigns a new tarea_revision as @tarea_revision" do
      get :new, {}, valid_session
      assigns(:tarea_revision).should be_a_new(TareaRevision)
    end
  end

  describe "GET edit" do
    it "assigns the requested tarea_revision as @tarea_revision" do
      tarea_revision = TareaRevision.create! valid_attributes
      get :edit, {:id => tarea_revision.to_param}, valid_session
      assigns(:tarea_revision).should eq(tarea_revision)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TareaRevision" do
        expect {
          post :create, {:tarea_revision => valid_attributes}, valid_session
        }.to change(TareaRevision, :count).by(1)
      end

      it "assigns a newly created tarea_revision as @tarea_revision" do
        post :create, {:tarea_revision => valid_attributes}, valid_session
        assigns(:tarea_revision).should be_a(TareaRevision)
        assigns(:tarea_revision).should be_persisted
      end

      it "redirects to the created tarea_revision" do
        post :create, {:tarea_revision => valid_attributes}, valid_session
        response.should redirect_to(TareaRevision.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tarea_revision as @tarea_revision" do
        # Trigger the behavior that occurs when invalid params are submitted
        TareaRevision.any_instance.stub(:save).and_return(false)
        post :create, {:tarea_revision => {}}, valid_session
        assigns(:tarea_revision).should be_a_new(TareaRevision)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TareaRevision.any_instance.stub(:save).and_return(false)
        post :create, {:tarea_revision => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tarea_revision" do
        tarea_revision = TareaRevision.create! valid_attributes
        # Assuming there are no other tarea_revisions in the database, this
        # specifies that the TareaRevision created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TareaRevision.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tarea_revision.to_param, :tarea_revision => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tarea_revision as @tarea_revision" do
        tarea_revision = TareaRevision.create! valid_attributes
        put :update, {:id => tarea_revision.to_param, :tarea_revision => valid_attributes}, valid_session
        assigns(:tarea_revision).should eq(tarea_revision)
      end

      it "redirects to the tarea_revision" do
        tarea_revision = TareaRevision.create! valid_attributes
        put :update, {:id => tarea_revision.to_param, :tarea_revision => valid_attributes}, valid_session
        response.should redirect_to(tarea_revision)
      end
    end

    describe "with invalid params" do
      it "assigns the tarea_revision as @tarea_revision" do
        tarea_revision = TareaRevision.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TareaRevision.any_instance.stub(:save).and_return(false)
        put :update, {:id => tarea_revision.to_param, :tarea_revision => {}}, valid_session
        assigns(:tarea_revision).should eq(tarea_revision)
      end

      it "re-renders the 'edit' template" do
        tarea_revision = TareaRevision.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TareaRevision.any_instance.stub(:save).and_return(false)
        put :update, {:id => tarea_revision.to_param, :tarea_revision => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tarea_revision" do
      tarea_revision = TareaRevision.create! valid_attributes
      expect {
        delete :destroy, {:id => tarea_revision.to_param}, valid_session
      }.to change(TareaRevision, :count).by(-1)
    end

    it "redirects to the tarea_revisions list" do
      tarea_revision = TareaRevision.create! valid_attributes
      delete :destroy, {:id => tarea_revision.to_param}, valid_session
      response.should redirect_to(tarea_revisions_url)
    end
  end

end
