require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipoOrganizacionsController do

  # This should return the minimal set of attributes required to create a valid
  # TipoOrganizacion. As you add validations to TipoOrganizacion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipoOrganizacionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tipo_organizacions as @tipo_organizacions" do
      tipo_organizacion = TipoOrganizacion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipo_organizacions).should eq([tipo_organizacion])
    end
  end

  describe "GET show" do
    it "assigns the requested tipo_organizacion as @tipo_organizacion" do
      tipo_organizacion = TipoOrganizacion.create! valid_attributes
      get :show, {:id => tipo_organizacion.to_param}, valid_session
      assigns(:tipo_organizacion).should eq(tipo_organizacion)
    end
  end

  describe "GET new" do
    it "assigns a new tipo_organizacion as @tipo_organizacion" do
      get :new, {}, valid_session
      assigns(:tipo_organizacion).should be_a_new(TipoOrganizacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipo_organizacion as @tipo_organizacion" do
      tipo_organizacion = TipoOrganizacion.create! valid_attributes
      get :edit, {:id => tipo_organizacion.to_param}, valid_session
      assigns(:tipo_organizacion).should eq(tipo_organizacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TipoOrganizacion" do
        expect {
          post :create, {:tipo_organizacion => valid_attributes}, valid_session
        }.to change(TipoOrganizacion, :count).by(1)
      end

      it "assigns a newly created tipo_organizacion as @tipo_organizacion" do
        post :create, {:tipo_organizacion => valid_attributes}, valid_session
        assigns(:tipo_organizacion).should be_a(TipoOrganizacion)
        assigns(:tipo_organizacion).should be_persisted
      end

      it "redirects to the created tipo_organizacion" do
        post :create, {:tipo_organizacion => valid_attributes}, valid_session
        response.should redirect_to(TipoOrganizacion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipo_organizacion as @tipo_organizacion" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoOrganizacion.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_organizacion => {}}, valid_session
        assigns(:tipo_organizacion).should be_a_new(TipoOrganizacion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoOrganizacion.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_organizacion => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipo_organizacion" do
        tipo_organizacion = TipoOrganizacion.create! valid_attributes
        # Assuming there are no other tipo_organizacions in the database, this
        # specifies that the TipoOrganizacion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TipoOrganizacion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tipo_organizacion.to_param, :tipo_organizacion => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tipo_organizacion as @tipo_organizacion" do
        tipo_organizacion = TipoOrganizacion.create! valid_attributes
        put :update, {:id => tipo_organizacion.to_param, :tipo_organizacion => valid_attributes}, valid_session
        assigns(:tipo_organizacion).should eq(tipo_organizacion)
      end

      it "redirects to the tipo_organizacion" do
        tipo_organizacion = TipoOrganizacion.create! valid_attributes
        put :update, {:id => tipo_organizacion.to_param, :tipo_organizacion => valid_attributes}, valid_session
        response.should redirect_to(tipo_organizacion)
      end
    end

    describe "with invalid params" do
      it "assigns the tipo_organizacion as @tipo_organizacion" do
        tipo_organizacion = TipoOrganizacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoOrganizacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_organizacion.to_param, :tipo_organizacion => {}}, valid_session
        assigns(:tipo_organizacion).should eq(tipo_organizacion)
      end

      it "re-renders the 'edit' template" do
        tipo_organizacion = TipoOrganizacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoOrganizacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_organizacion.to_param, :tipo_organizacion => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipo_organizacion" do
      tipo_organizacion = TipoOrganizacion.create! valid_attributes
      expect {
        delete :destroy, {:id => tipo_organizacion.to_param}, valid_session
      }.to change(TipoOrganizacion, :count).by(-1)
    end

    it "redirects to the tipo_organizacions list" do
      tipo_organizacion = TipoOrganizacion.create! valid_attributes
      delete :destroy, {:id => tipo_organizacion.to_param}, valid_session
      response.should redirect_to(tipo_organizacions_url)
    end
  end

end
