require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipoPlantillasController do

  # This should return the minimal set of attributes required to create a valid
  # TipoPlantilla. As you add validations to TipoPlantilla, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipoPlantillasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tipo_plantillas as @tipo_plantillas" do
      tipo_plantilla = TipoPlantilla.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipo_plantillas).should eq([tipo_plantilla])
    end
  end

  describe "GET show" do
    it "assigns the requested tipo_plantilla as @tipo_plantilla" do
      tipo_plantilla = TipoPlantilla.create! valid_attributes
      get :show, {:id => tipo_plantilla.to_param}, valid_session
      assigns(:tipo_plantilla).should eq(tipo_plantilla)
    end
  end

  describe "GET new" do
    it "assigns a new tipo_plantilla as @tipo_plantilla" do
      get :new, {}, valid_session
      assigns(:tipo_plantilla).should be_a_new(TipoPlantilla)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipo_plantilla as @tipo_plantilla" do
      tipo_plantilla = TipoPlantilla.create! valid_attributes
      get :edit, {:id => tipo_plantilla.to_param}, valid_session
      assigns(:tipo_plantilla).should eq(tipo_plantilla)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TipoPlantilla" do
        expect {
          post :create, {:tipo_plantilla => valid_attributes}, valid_session
        }.to change(TipoPlantilla, :count).by(1)
      end

      it "assigns a newly created tipo_plantilla as @tipo_plantilla" do
        post :create, {:tipo_plantilla => valid_attributes}, valid_session
        assigns(:tipo_plantilla).should be_a(TipoPlantilla)
        assigns(:tipo_plantilla).should be_persisted
      end

      it "redirects to the created tipo_plantilla" do
        post :create, {:tipo_plantilla => valid_attributes}, valid_session
        response.should redirect_to(TipoPlantilla.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipo_plantilla as @tipo_plantilla" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoPlantilla.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_plantilla => {}}, valid_session
        assigns(:tipo_plantilla).should be_a_new(TipoPlantilla)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TipoPlantilla.any_instance.stub(:save).and_return(false)
        post :create, {:tipo_plantilla => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipo_plantilla" do
        tipo_plantilla = TipoPlantilla.create! valid_attributes
        # Assuming there are no other tipo_plantillas in the database, this
        # specifies that the TipoPlantilla created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TipoPlantilla.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tipo_plantilla.to_param, :tipo_plantilla => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tipo_plantilla as @tipo_plantilla" do
        tipo_plantilla = TipoPlantilla.create! valid_attributes
        put :update, {:id => tipo_plantilla.to_param, :tipo_plantilla => valid_attributes}, valid_session
        assigns(:tipo_plantilla).should eq(tipo_plantilla)
      end

      it "redirects to the tipo_plantilla" do
        tipo_plantilla = TipoPlantilla.create! valid_attributes
        put :update, {:id => tipo_plantilla.to_param, :tipo_plantilla => valid_attributes}, valid_session
        response.should redirect_to(tipo_plantilla)
      end
    end

    describe "with invalid params" do
      it "assigns the tipo_plantilla as @tipo_plantilla" do
        tipo_plantilla = TipoPlantilla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoPlantilla.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_plantilla.to_param, :tipo_plantilla => {}}, valid_session
        assigns(:tipo_plantilla).should eq(tipo_plantilla)
      end

      it "re-renders the 'edit' template" do
        tipo_plantilla = TipoPlantilla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TipoPlantilla.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipo_plantilla.to_param, :tipo_plantilla => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipo_plantilla" do
      tipo_plantilla = TipoPlantilla.create! valid_attributes
      expect {
        delete :destroy, {:id => tipo_plantilla.to_param}, valid_session
      }.to change(TipoPlantilla, :count).by(-1)
    end

    it "redirects to the tipo_plantillas list" do
      tipo_plantilla = TipoPlantilla.create! valid_attributes
      delete :destroy, {:id => tipo_plantilla.to_param}, valid_session
      response.should redirect_to(tipo_plantillas_url)
    end
  end

end
